
CC = gcc
FLAGS = -ggdb3

all:
	$(CC) main.c Map/map.c LinkedList/linked_list.c Stack/stack.c -o a

build:
	$(CC) $(FLAGS)  main.c Map/map.c LinkedList/linked_list.c Stack/stack.c -o a



clean:
	rm -rf *.o
	rm -rf a

